apiVersion: v1
kind: Service
metadata:
  name: wordsmith-api-svc
  labels:
    app: wordsmith-api-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: wsapiport
  selector:
    app: wordsmith-api-label
  clusterIP: None