apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordsmith-db-statefulset
spec:
  serviceName: wordsmith-db-statefulset
  selector:
    matchLabels:
      app: wordsmith-db-label
  template:
    metadata:
      labels:
        app: wordsmith-db-label
        environment: wordsmith-test-env
    spec:
      containers:
        - name: wordsmith-db-container
          image: elyhamza/wordsmith-db
          volumeMounts:
            - name: wordsmith-db-disk
              mountPath: /var/lib/postgresql/data
          envFrom:
          - secretRef:
              name: wordsmith-secrets
          ports:
            - containerPort: 5432
              name: wordsmithdbport
  volumeClaimTemplates:
    - metadata:
        name: wordsmith-db-disk
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 25Gi